version: '3'
services:
  agiletc:
    image: tuimeo/agile-tc:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/case_manager?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      - WEB_UPLOADPATH=/app/uploads
      - TZ=Asia/Shanghai
    ports:
      - "8094:8094"
      - "8095:8095"
    volumes:
      - ./data/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./case-server.sql:/docker-entrypoint-initdb.d/init_agiletc.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=case_manager
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost",'-u', 'root', '-proot']
      timeout: 5s
      retries: 10